# Generated by Django 4.2.20 on 2025-04-04 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentorados', '0005_upload_tarefa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='mentorado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorados.mentorados'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='mentorado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorados.mentorados'),
        ),
    ]
