# Generated by Django 4.2.20 on 2025-04-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorados', '0006_alter_tarefa_mentorado_alter_upload_mentorado'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorados',
            name='senha',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
